@startuml
'https://plantuml.com/deployment-diagram

actor Human
card GrandRhombus

package Command
package Data {
    card UserMod
    card Mod
}
Mod <-> UserMod

package Storage {
    card ModStorage
    card UserStorage
}

package Errors {
    card ErrorHandler
}

folder resources {
    file moduledata.txt
}

package User {
}

card CommandParser
card Ui
file user.txt

Human -> GrandRhombus
GrandRhombus --> UserStorage
GrandRhombus --> User
GrandRhombus -> Ui
GrandRhombus --> CommandParser

CommandParser --> Command
Command --> User
UserStorage <--> User
UserStorage --> user.txt
User --> UserMod
ModStorage -> moduledata.txt
ModStorage <--> Mod



@enduml