@startuml
'https://plantuml.com/sequence-diagram

hide circle
skinparam classAttributeIconSize 0

card CommandParser

card Command

card Ui

card ErrorHandler

input --> CommandParser
CommandParser --> Command
CommandParser --> ErrorHandler
ErrorHandler -d-> Ui

@enduml